site_name: Manteia AI Playbook
site_description: Linee guida e blueprint per sviluppo AI production-grade (SCRUM, CI/CD, Agentic RAG, ReAct, MCP)
site_author: Manteia
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
docs_dir: docs
use_directory_urls: true
nav:
  - Home: index.md
  - Visione: vision.md
  - Ways of Working: ways-of-working.md
  - Test: testing-strategy.md
  - CI/CD: ci-cd.md
  - MLOps & LLMOps: mlops-llmops.md
  - Security & Privacy: policies/security-privacy.md
  - Observability: practices/observability.md
  - LLM Testing: practices/llm-testing-playbook.md
  - Blueprint:
    - Agentic + ReAct: blueprints/agentic-arch-blueprint.md
    - MCP: blueprints/mcp-playbook.md
    - RAG: blueprints/rag-blueprint.md
  - Policies:
    - Release & Versioning: policies/release-versioning.md
  - Runbooks:
    - Incident Response: runbooks/incident-response.md
  - Templates:
    - ADR: template/13-adr-template.md
    - Project structure: template/14-project-structure.md
  - Onboarding: onboarding-checklist.md
